version: "3"
services:
  api:
    build: ./api
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    volumes:
      - "api:/repo"
      - "api.go.1.18:/go"
    ports:
      - "8080:8080"
      - "8081:8081"
    tty: true
  proxy-backward-bff:
    build: ./proxy/backward
    ports:
      - "8001:8001"
    tty: true
    volumes:
      - "proxy-backward-bff:/repo"
    depends_on:
      - api
  proxy-conversion:
    build: ./proxy/conversion
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - proxy-backward-bff
  client-go:
    build: ./client-go
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    volumes:
      - "client-go:/repo"
      - "client-go.go.1.18:/go"
    tty: true
    depends_on:
      - api
  client-ruby:
    build: ./client-ruby
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    volumes:
      - "client-ruby:/repo"
    tty: true
    depends_on:
      - api
  web:
    build: ./web
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    volumes:
      - "web:/repo"
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - proxy-backward-bff
volumes:
  api:
  api.go.1.18:
  client-go:
  client-go.go.1.18:
  client-ruby:
  web:
  proxy-backward-bff:
