version: "3"

services:
  protoc-go:
    build: ./protoc-go
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    volumes:
      - "protoc-go:/repo"
      - "protoc-go.go.1.13:/go"
    ports:
      - "52300:52300"
    tty: true
  api:
    build: ./api
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    volumes:
      - "api:/repo"
      - "api.go.1.13:/go"
    ports:
      - "8080:8080"
    tty: true
  proxy:
    build: ./proxy
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - api
  client:
    build: ./client
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    volumes:
      - "client:/repo"
      - "client.go.1.13:/go"
    tty: true
    depends_on:
      - api
  web:
    build: ./web
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    volumes:
      - "web:/repo"
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - proxy
volumes:
  protoc-go:
  protoc-go.go.1.13:
  api:
  api.go.1.13:
  client:
  client.go.1.13:
  web:
