version: "3"
services:
  api:
    build: ./api
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    volumes:
      - "api:/repo"
      - "api.go.1.13:/go"
    ports:
      - "8080:8080"
      - "52300:52300"
    tty: true
  proxy:
    build: ./proxy
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - api
  client-go:
    build: ./client-go
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    volumes:
      - "client-go:/repo"
      - "client-go.go.1.13:/go"
    tty: true
    depends_on:
      - api
  client-ruby:
    build: ./client-ruby
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    volumes:
      - "client-ruby:/repo"
    tty: true
    depends_on:
      - api
  web:
    build: ./web
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    volumes:
      - "web:/repo"
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - proxy
volumes:
  api:
  api.go.1.13:
  client-go:
  client-go.go.1.13:
  client-ruby:
  web:
